server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://loki.nofamex.tech/loki/api/v1/push

scrape_configs:
  - job_name: local
    static_configs:
      - targets:
          - localhost
        labels:
          job: promo-logs
          __path__: /var/promo/*.log
